# Generated by Django 5.1.15 on 2026-08-11 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nit', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('contact_name', models.CharField(blank=True, default='', max_length=200)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets_hospital',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetCustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type_name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('DATE', 'Fecha'), ('BOOLEAN', 'Sí/No'), ('SELECT', 'Selección'), ('TEXTAREA', 'Texto largo')], max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('options', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets_assetcustomfield',
                'ordering': ['asset_type_name', 'sort_order'],
                'constraints': [models.UniqueConstraint(fields=('asset_type_name', 'field_name'), name='uq_customfield_type_name')],
            },
        ),
        migrations.CreateModel(
            name='AssetNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('AREA', 'Área / Servicio'), ('FLOOR', 'Piso'), ('BUILDING', 'Edificio/Torre'), ('ROOM', 'Habitación/Sala'), ('OTHER', 'Otro')], default='AREA', max_length=10)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('path', models.CharField(blank=True, default='', help_text='Ruta materializada auto-generada. No editar manualmente.', max_length=1000)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Nodo padre. NULL = nodo raíz directo del hospital', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='assets.assetnode')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_nodes', to='assets.hospital')),
            ],
            options={
                'db_table': 'assets_assetnode',
                'ordering': ['hospital', 'path'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=200)),
                ('equipment_location', models.CharField(blank=True, default='', max_length=255)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=10)),
                ('asset_type', models.CharField(blank=True, default='', max_length=100)),
                ('classification_1', models.CharField(blank=True, default='', max_length=100)),
                ('classification_2', models.CharField(blank=True, default='', max_length=100)),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('avg_daily_usage_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('OUT_OF_SERVICE', 'Fuera de servicio'), ('DECOMMISSIONED', 'Dado de baja')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('qr_code', models.CharField(blank=True, default='', max_length=255)),
                ('photo_url', models.CharField(blank=True, default='', max_length=500)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetnode')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.hospital')),
            ],
            options={
                'db_table': 'assets_asset',
                'ordering': ['hospital', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetCustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_field_values', to='assets.asset')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='assets.assetcustomfield')),
            ],
            options={
                'db_table': 'assets_assetcustomfieldvalue',
                'constraints': [models.UniqueConstraint(fields=('asset', 'field'), name='uq_customfieldvalue_asset_field')],
            },
        ),
        migrations.AddConstraint(
            model_name='assetnode',
            constraint=models.UniqueConstraint(fields=('hospital', 'parent', 'name'), name='uq_assetnode_hospital_parent_name'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['hospital', 'status'], name='idx_asset_hospital_status'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='idx_asset_serial'),
        ),
    ]
