# Generated by Django 5.1.15 on 2026-09-02 19:54

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        # pg_trgm tiene que existir antes que los indices: gin_trgm_ops es
        # suya. Desde PostgreSQL 13 es una extension "trusted", asi que la
        # crea el propietario de la base sin necesidad de superusuario.
        TrigramExtension(),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='idx_asset_name_trgm'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('code'), name='gin_trgm_ops'), name='idx_asset_code_trgm'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('serial_number'), name='gin_trgm_ops'), name='idx_asset_serial_trgm'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('model'), name='gin_trgm_ops'), name='idx_asset_model_trgm'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('manufacturer'), name='gin_trgm_ops'), name='idx_asset_manuf_trgm'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='idx_hospital_name_trgm'),
        ),
    ]
