# Generated by Django 5.1.15 on 2026-09-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_search_trigram_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcustomfieldvalue',
            options={'ordering': ['asset', 'field']},
        ),
    ]
