# Generated by Django 5.1.15 on 2026-09-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_plan_tasks_and_tasks'),
        ('maintenance', '0004_drop_legacy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='maintenance.maintenanceplan'),
        ),
    ]
