# Generated by Django 5.1.15 on 2026-09-23 22:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_drop_legacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('MAINTENANCE', 'Contrato de mantenimiento'), ('WARRANTY', 'Garantía de equipos')], max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_key', models.CharField(blank=True, default='', max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_notice', models.CharField(blank=True, choices=[('', 'Ninguno'), ('60', '60 días'), ('30', '30 días'), ('EXPIRED', 'Vencido')], default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.hospital')),
                ('node', models.ForeignKey(blank=True, help_text='Solo contratos: la parte del arbol que cubre. Vacio = todo el hospital.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='assets.assetnode')),
            ],
            options={
                'db_table': 'assets_contract',
                'ordering': ['-end_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContractAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_links', to='assets.asset')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='assets.contract')),
            ],
            options={
                'db_table': 'assets_contractasset',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='contracts', through='assets.ContractAsset', to='assets.asset'),
        ),
        migrations.AddConstraint(
            model_name='contractasset',
            constraint=models.UniqueConstraint(fields=('contract', 'asset'), name='uq_contractasset'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['hospital', 'kind', 'end_date'], name='idx_contract_hosp_kind_end'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_contract_end_after_start'),
        ),
    ]
