# Generated by Django 5.1.15 on 2026-09-24 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_contratos_y_garantias'),
        ('checklists', '0007_bloques_repetibles'),
        ('maintenance', '0007_sembrar_tipos_de_tarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('is_counter', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assets_meterunit',
                'ordering': ['sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'symbol'), name='uq_meterunit_name_symbol')],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='assets.asset')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='assets.meterunit')),
            ],
            options={
                'db_table': 'assets_meter',
                'ordering': ['asset', 'unit__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('accumulated', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('read_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('CHECKLIST', 'Checklist'), ('MANUAL', 'Registro manual')], max_length=10)),
                ('is_reset', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meter_reading', to='checklists.checklistfieldresponse')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='assets.meter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='meter_readings', to='maintenance.task')),
            ],
            options={
                'db_table': 'assets_meterreading',
                'ordering': ['-read_at', '-created_at'],
                'indexes': [models.Index(fields=['meter', 'read_at'], name='idx_reading_meter_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('asset', 'unit'), name='uq_meter_asset_unit'),
        ),
    ]
