# Generated by Django 5.1.15 on 2026-08-11 03:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('checklists', '0001_initial'),
        ('maintenance', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wo_number', models.PositiveIntegerField(help_text='Número legible auto-incremental. Fracttal: 19190, 19197, etc.', unique=True)),
                ('task_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('VERIFICATION', 'Verificación'), ('INSTALLATION', 'Instalación'), ('DELIVERY', 'Entrega')], max_length=15)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('classification_1', models.CharField(blank=True, default='', max_length=100)),
                ('classification_2', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('IN_REVIEW', 'En Revisión'), ('COMPLETED', 'Finalizada'), ('CANCELLED', 'Cancelada')], db_index=True, default='PENDING', max_length=15)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=10)),
                ('progress', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_measure', models.CharField(choices=[('SUBTASKS', 'Todas las subtareas'), ('MANUAL', 'Manual')], default='SUBTASKS', max_length=10)),
                ('scheduled_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('actual_duration', models.DurationField(blank=True, null=True)),
                ('downtime', models.DurationField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='')),
                ('request_number', models.IntegerField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('offline_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('checklist_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='checklists.checklisttemplateversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_work_orders', to='maintenance.maintenanceplan')),
            ],
            options={
                'db_table': 'work_orders_workorder',
                'ordering': ['-wo_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('IN_REVIEW', 'En Revisión'), ('COMPLETED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='', max_length=15)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En Proceso'), ('IN_REVIEW', 'En Revisión'), ('COMPLETED', 'Finalizada'), ('CANCELLED', 'Cancelada')], max_length=15)),
                ('comment', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wo_status_changes', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'work_orders_workorderstatushistory',
                'ordering': ['work_order', 'changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'assigned_to'], name='idx_wo_status_assignee'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['asset', 'status'], name='idx_wo_asset_status'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_date'], name='idx_wo_scheduled_date'),
        ),
    ]
