# Generated by Django 5.1.15 on 2026-09-03 15:39

from django.db import migrations, models


def backfill_wo_year(apps, schema_editor):
    """
    Rellena wo_year en las OTs existentes con el año de created_at.

    Sin esto, wo_code de una OT anterior a esta migración caería al fallback
    sin año (OT-00001) hasta que la fila se vuelva a guardar. created_at existe
    desde 0001 (auto_now_add), así que siempre hay un año fiable.
    """
    WorkOrder = apps.get_model('work_orders', 'WorkOrder')
    for wo in WorkOrder.objects.filter(wo_year__isnull=True).only('id', 'created_at'):
        WorkOrder.objects.filter(pk=wo.pk).update(wo_year=wo.created_at.year)


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='wo_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Año de creación. Solo compone el número legible (wo_code).', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_number',
            field=models.PositiveIntegerField(help_text='Secuencial global. Se muestra siempre a través de wo_code.', unique=True),
        ),
        migrations.RunPython(backfill_wo_year, migrations.RunPython.noop),
    ]
