# Generated by Django 5.1.15 on 2026-09-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_plan_tasks_and_tasks'),
        ('work_orders', '0003_workorder_wo_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.hospital'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Zona de la visita ("Piso 3"). Opcional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.assetnode'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset'),
        ),
    ]
