# Generated by Django 5.1.15 on 2026-09-21 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_drop_legacy_fields'),
        ('work_orders', '0004_plan_tasks_and_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workorder',
            name='idx_wo_asset_status',
        ),
        migrations.RemoveIndex(
            model_name='workorder',
            name='idx_wo_plan_status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='checklist_version',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='maintenance_plan',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.hospital'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['hospital', 'status'], name='idx_wo_hospital_status'),
        ),
    ]
