# Generated by Django 5.1.15 on 2026-09-23 19:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_drop_legacy_fields'),
        ('maintenance', '0005_bloques_repetibles'),
        ('work_orders', '0005_drop_legacy_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('out_of_service', models.BooleanField(default=False, help_text='El equipo queda fuera de servicio por este hallazgo.')),
                ('resolved_on_site', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Qué se hizo en sitio, si se resolvió ahí.')),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('RESOLVED', 'Resuelto en sitio'), ('PENDING', 'Pendiente'), ('CONVERTED', 'Convertido en correctivo'), ('DISMISSED', 'Descartado')], default='PENDING', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='assets.asset')),
                ('corrective_task', models.OneToOneField(blank=True, help_text='La tarea correctiva pendiente que se creo a partir de este hallazgo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_finding', to='maintenance.task')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_findings', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_findings', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'work_orders_finding',
                'ordering': ['work_order', 'reported_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='idx_finding_status_sev')],
            },
        ),
    ]
