# Generated by Django 5.1.15 on 2026-09-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0006_hallazgos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='task_type',
            field=models.CharField(max_length=50),
        ),
    ]
