# Generated by Django 5.1.15 on 2026-08-11 03:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('PUSH', 'Push notification'), ('EMAIL', 'Correo electrónico'), ('SMS', 'SMS'), ('IN_APP', 'Notificación in-app')], max_length=6)),
                ('notification_type', models.CharField(choices=[('WO_ASSIGNED', 'OT asignada'), ('WO_COMPLETED', 'OT completada'), ('WO_OVERDUE', 'OT vencida'), ('PLAN_GENERATED', 'Plan generó OTs'), ('STOCK_LOW', 'Stock bajo'), ('GENERAL', 'General')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notificationlog',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'sent_at'], name='idx_notif_user_read')],
            },
        ),
    ]
