# Generated by Django 5.1.15 on 2026-08-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Obliga al usuario a cambiar la contraseña en el próximo login.'),
        ),
    ]
