# Generated by Django 5.1.15 on 2026-09-23 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Solo necesita AssetNode, que existe desde la primera: depender de la
        # ultima de assets hacia que retroceder assets deshiciera esta tambien.
        ('assets', '0001_initial'),
        ('users', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scope_node',
            field=models.ForeignKey(blank=True, help_text='Parte del hospital a la que se limita el usuario. Vacío: todo el hospital.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_users', to='assets.assetnode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital al que se limita lo que ve el usuario (obligatorio para CLI). Vacío: todos. No aplica a ADMIN.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='assets.hospital'),
        ),
    ]
