# Generated by Django 5.1.15 on 2026-08-11 03:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('checklists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('VERIFICATION', 'Verificación'), ('INSTALLATION', 'Instalación'), ('DELIVERY', 'Entrega')], default='PREVENTIVE', max_length=15)),
                ('classification_1', models.CharField(blank=True, default='', max_length=100)),
                ('classification_2', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=10)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('downtime_duration', models.DurationField(blank=True, null=True)),
                ('frequency_value', models.PositiveIntegerField(default=6)),
                ('frequency_unit', models.CharField(choices=[('DAYS', 'Días'), ('WEEKS', 'Semanas'), ('MONTHS', 'Meses'), ('YEARS', 'Años')], default='MONTHS', max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('fracttal_plan_id', models.CharField(blank=True, default='', help_text='ID del plan en Fracttal para trazabilidad de migracion.', max_length=50)),
                ('fracttal_task_id', models.CharField(blank=True, default='', help_text='ID de la tarea en Fracttal para trazabilidad de migracion.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='maintenance_plans', to='assets.asset')),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='checklists.checklisttemplate')),
                ('restrict_to_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='assets.hospital')),
            ],
            options={
                'db_table': 'maintenance_maintenanceplan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlanExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_orders_created', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_executions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='maintenance.maintenanceplan')),
            ],
            options={
                'db_table': 'maintenance_maintenanceplanexecution',
                'ordering': ['-executed_at'],
            },
        ),
    ]
