# Generated by Django 5.1.15 on 2026-09-21 14:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_plan_tasks_and_tasks'),
        ('checklists', '0004_default_ordering'),
        ('maintenance', '0001_initial'),
        ('work_orders', '0004_plan_tasks_and_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescheduleCause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'maintenance_reschedulecause',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('VERIFICATION', 'Verificación'), ('INSTALLATION', 'Instalación'), ('DELIVERY', 'Entrega')], default='PREVENTIVE', max_length=15)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=10)),
                ('trigger', models.CharField(choices=[('DATE', 'Fecha'), ('EVENT', 'Evento')], default='DATE', max_length=5)),
                ('frequency_value', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency_unit', models.CharField(blank=True, choices=[('DAYS', 'Días'), ('WEEKS', 'Semanas'), ('MONTHS', 'Meses'), ('YEARS', 'Años')], default='', max_length=6)),
                ('repeat_count', models.PositiveIntegerField(blank=True, help_text='Vacio = se repite siempre. N = se ejecuta N veces y no se vuelve a generar (Fracttal: Repetir por N).', null=True)),
                ('fixed_schedule', models.BooleanField(default=False, help_text='Con programacion fija la siguiente fecha calculada sale de la calculada anterior; sin ella, de la fecha de realizacion. Fracttal la trae desmarcada y asi la usa el cliente.')),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('downtime_duration', models.DurationField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Fecha calculada de la primera ocurrencia en cada activo. Vacio = el dia en que el activo recibe el plan.', null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('fracttal_task_id', models.CharField(blank=True, default='', help_text='ID de la tarea en Fracttal para trazabilidad de migracion.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_tasks', to='checklists.checklisttemplate')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='maintenance.maintenanceplan')),
            ],
            options={
                'db_table': 'maintenance_plantask',
                'ordering': ['plan', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SCHEDULED', 'Programada'), ('DONE', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('task_type', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('VERIFICATION', 'Verificación'), ('INSTALLATION', 'Instalación'), ('DELIVERY', 'Entrega')], max_length=15)),
                ('priority', models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', max_length=10)),
                ('calculated_date', models.DateField()),
                ('scheduled_date', models.DateField()),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_note', models.TextField(blank=True, default='', help_text='Por que se cancelo: OT cancelada, cambio de plan, anulada a mano.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='assets.asset')),
                ('checklist_version', models.ForeignKey(blank=True, help_text='Se fija al meter la tarea en una OT, no al crearla: una pendiente que espera meses no debe ejecutarse con una version vieja del checklist.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='checklists.checklisttemplateversion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('plan_task', models.ForeignKey(blank=True, help_text='Vacio en las tareas creadas a mano (correctivos).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='maintenance.plantask')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'maintenance_task',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReschedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedules', to='maintenance.reschedulecause')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_reschedules', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedules', to='maintenance.task')),
            ],
            options={
                'db_table': 'maintenance_taskreschedule',
                'ordering': ['task', 'changed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='plantask',
            constraint=models.CheckConstraint(condition=models.Q(('trigger', 'EVENT'), models.Q(('frequency_value__isnull', False), models.Q(('frequency_unit', ''), _negated=True)), _connector='OR'), name='ck_plantask_date_trigger_has_frequency'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'scheduled_date'], name='idx_task_status_scheduled'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['asset', 'status'], name='idx_task_asset_status'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'SCHEDULED'])), fields=('plan_task', 'asset'), name='uq_task_one_open_per_plantask_asset'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PENDING'), ('work_order__isnull', True)), models.Q(('status__in', ['SCHEDULED', 'DONE']), ('work_order__isnull', False)), ('status', 'CANCELLED'), _connector='OR'), name='ck_task_status_matches_work_order'),
        ),
    ]
