# Generated by Django 5.1.15 on 2026-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_move_to_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='assets',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='checklist_template',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='downtime_duration',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='fracttal_task_id',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='frequency_unit',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='frequency_value',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='last_generated_at',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='maintenanceplan',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='maintenanceplan',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'Alta'), ('MEDIUM', 'Media'), ('LOW', 'Baja')], default='MEDIUM', help_text='Prioridad por defecto de las tareas nuevas del plan.', max_length=10),
        ),
    ]
