# Generated by Django 5.1.15 on 2026-09-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_drop_legacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantask',
            name='block_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
