# Generated by Django 5.1.15 on 2026-09-23 23:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_bloques_repetibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypeCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('counts_as', models.CharField(choices=[('PREVENTIVE', 'Preventivo'), ('CORRECTIVE', 'Correctivo'), ('OTHER', 'Ninguno')], default='OTHER', max_length=10)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_tasktype',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='plantask',
            name='task_type',
            field=models.CharField(default='PREVENTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(max_length=50),
        ),
    ]
