# Generated by Django 5.1.15 on 2026-09-24 18:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_medidores_y_lecturas'),
        ('checklists', '0007_bloques_repetibles'),
        ('maintenance', '0007_sembrar_tipos_de_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('next_due', models.DecimalField(decimal_places=3, max_digits=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_meterschedule',
            },
        ),
        migrations.RemoveConstraint(
            model_name='plantask',
            name='ck_plantask_date_trigger_has_frequency',
        ),
        migrations.AddField(
            model_name='plantask',
            name='meter_comparator',
            field=models.CharField(blank=True, choices=[('EQ', 'Igual a'), ('NE', 'Diferente a'), ('GT', 'Mayor que'), ('GTE', 'Mayor o igual a'), ('LT', 'Menor que'), ('LTE', 'Menor o igual a')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='plantask',
            name='meter_interval',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='plantask',
            name='meter_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='plantask',
            name='meter_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_tasks', to='assets.meterunit'),
        ),
        migrations.AddField(
            model_name='task',
            name='meter_due',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='trigger_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_tasks', to='assets.meterreading'),
        ),
        migrations.AlterField(
            model_name='plantask',
            name='trigger',
            field=models.CharField(choices=[('DATE', 'Fecha'), ('EVENT', 'Evento'), ('EVERY', 'Cada N unidades del medidor'), ('WHEN', 'Cuando la lectura cruza un umbral')], default='DATE', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='plantask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trigger', 'DATE'), _negated=True), models.Q(('frequency_value__isnull', False), models.Q(('frequency_unit', ''), _negated=True)), _connector='OR'), name='ck_plantask_date_trigger_has_frequency'),
        ),
        migrations.AddConstraint(
            model_name='plantask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trigger', 'EVERY'), _negated=True), models.Q(('meter_unit__isnull', False), ('meter_interval__gt', 0)), _connector='OR'), name='ck_plantask_every_has_interval'),
        ),
        migrations.AddConstraint(
            model_name='plantask',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('trigger', 'WHEN'), _negated=True), models.Q(('meter_unit__isnull', False), models.Q(('meter_comparator', ''), _negated=True), ('meter_threshold__isnull', False)), _connector='OR'), name='ck_plantask_when_has_threshold'),
        ),
        migrations.AddField(
            model_name='meterschedule',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_schedules', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='meterschedule',
            name='plan_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meter_schedules', to='maintenance.plantask'),
        ),
        migrations.AddConstraint(
            model_name='meterschedule',
            constraint=models.UniqueConstraint(fields=('plan_task', 'asset'), name='uq_meterschedule_plantask_asset'),
        ),
    ]
