# Generated by Django 5.1.15 on 2026-08-11 03:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=500)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('taken_at', models.DateTimeField()),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('offline_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'evidence_photo',
                'ordering': ['work_order', 'taken_at'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_type', models.CharField(choices=[('TECHNICIAN', 'Firma del técnico'), ('CLIENT', 'Firma del cliente')], max_length=12)),
                ('file_url', models.CharField(max_length=500)),
                ('signer_name', models.CharField(max_length=200)),
                ('signer_role', models.CharField(blank=True, default='', max_length=100)),
                ('file_hash', models.CharField(max_length=64)),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'evidence_signature',
                'constraints': [models.UniqueConstraint(fields=('work_order', 'signature_type'), name='uq_signature_wo_type')],
            },
        ),
    ]
