# Generated by Django 5.1.15 on 2026-09-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_signature_immutable_triggers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signature',
            options={'ordering': ['work_order', 'signature_type']},
        ),
    ]
