# Generated by Django 5.1.15 on 2026-09-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_default_ordering'),
        ('maintenance', '0002_plan_tasks_and_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='maintenance.task'),
        ),
    ]
