# Generated by Django 5.1.15 on 2026-09-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_photo_task'),
        ('work_orders', '0006_hallazgos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='work_orders.finding'),
        ),
    ]
