# Generated by Django 5.1.15 on 2026-08-11 03:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('TEXT', 'Texto libre'), ('NUMBER', 'Valor numérico'), ('BOOLEAN', 'Sí/No (checkbox)'), ('SELECT', 'Selección única'), ('MULTI_SELECT', 'Selección múltiple'), ('PHOTO', 'Fotografía'), ('SIGNATURE', 'Firma digital'), ('GPS', 'Localización GPS'), ('METER', 'Lectura de medidor'), ('DATE', 'Fecha'), ('DATETIME', 'Fecha y hora'), ('TEXTAREA', 'Texto largo')], max_length=15)),
                ('group', models.CharField(blank=True, default='', max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('options_json', models.JSONField(blank=True, default=list)),
                ('help_text', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checklists_checklistfield',
                'ordering': ['version', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'checklists_checklisttemplate',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checklists_checklisttemplateversion',
                'ordering': ['template', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistFieldResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklistfield')),
            ],
            options={
                'db_table': 'checklists_checklistfieldresponse',
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checklists_checklistresponse',
            },
        ),
    ]
