# Generated by Django 5.1.15 on 2026-08-11 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklists', '0001_initial'),
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_response', to='work_orders.workorder'),
        ),
        migrations.AddField(
            model_name='checklistfieldresponse',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_responses', to='checklists.checklistresponse'),
        ),
        migrations.AddField(
            model_name='checklisttemplateversion',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_checklist_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklisttemplateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='checklists.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklisttemplateversion'),
        ),
        migrations.AddField(
            model_name='checklistfield',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='checklists.checklisttemplateversion'),
        ),
        migrations.AddConstraint(
            model_name='checklistfieldresponse',
            constraint=models.UniqueConstraint(fields=('response', 'field'), name='uq_fieldresponse_response_field'),
        ),
        migrations.AddConstraint(
            model_name='checklisttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='uq_checklist_version'),
        ),
    ]
