# Generated by Django 5.1.15 on 2026-09-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_checklistresponse_work_order_notnull'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistfieldresponse',
            options={'ordering': ['field__group', 'field__sort_order']},
        ),
        migrations.AlterModelOptions(
            name='checklistresponse',
            options={'ordering': ['-created_at']},
        ),
    ]
