# Generated by Django 5.1.15 on 2026-09-21 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_default_ordering'),
        ('maintenance', '0002_plan_tasks_and_tasks'),
        ('work_orders', '0004_plan_tasks_and_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistresponse',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_response', to='maintenance.task'),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_response', to='work_orders.workorder'),
        ),
    ]
