# Generated by Django 5.1.15 on 2026-09-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_plan_tasks_and_tasks'),
        ('maintenance', '0004_drop_legacy_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistresponse',
            name='work_order',
        ),
        migrations.AlterField(
            model_name='checklistresponse',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_response', to='maintenance.task'),
        ),
    ]
