# Generated by Django 5.1.15 on 2026-09-22 22:47

from django.db import migrations, models


def _sin_tomas_respondidas(apps, schema_editor):
    """
    Volver atras quita la repeticion y restituye un campo = una respuesta. Si
    ya hay tomas respondidas, eso no cabe: se detiene con el motivo en vez de
    fallar con un error de unicidad de la base.
    """
    FieldResponse = apps.get_model("checklists", "ChecklistFieldResponse")
    n = FieldResponse.objects.filter(repetition__gt=0).count()
    if n:
        raise RuntimeError(
            f"No se puede revertir: hay {n} respuestas de bloques repetibles "
            "(tomas). El esquema anterior guarda una sola respuesta por campo."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_drop_legacy_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistfieldresponse',
            options={'ordering': ['field__group', 'repetition', 'field__sort_order']},
        ),
        migrations.RemoveConstraint(
            model_name='checklistfieldresponse',
            name='uq_fieldresponse_response_field',
        ),
        migrations.AddField(
            model_name='checklistfieldresponse',
            name='repetition',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='block_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='checklistresponse',
            name='planned_block_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='checklisttemplateversion',
            name='repeatable_groups',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='checklistfieldresponse',
            constraint=models.UniqueConstraint(fields=('response', 'field', 'repetition'), name='uq_fieldresponse_response_field_rep'),
        ),
        # Va al final porque al revertir las operaciones corren al reves: asi
        # comprueba primero, cuando la columna repetition todavia existe.
        migrations.RunPython(migrations.RunPython.noop, _sin_tomas_respondidas),
    ]
