# Generated by Django 5.1.15 on 2026-09-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_bloques_repetibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistfieldresponse',
            name='geo_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
