# Generated by Django 5.1.15 on 2026-08-11 03:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('WORK_ORDER', 'Reporte de OT'), ('MAINTENANCE', 'Reporte de mantenimiento'), ('DELIVERY', 'Acta de entrega'), ('CUSTOM', 'Personalizado')], max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='work_orders.workorder')),
            ],
            options={
                'db_table': 'reports_generatedreport',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSendLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=200)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('was_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_logs', to='reports.generatedreport')),
            ],
            options={
                'db_table': 'reports_reportsendlog',
                'ordering': ['-sent_at'],
            },
        ),
    ]
