# Generated by Django 5.1.15 on 2026-09-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='integrity_version',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
